import turtle

turtle.speed(10)

turtle.penup()
turtle.goto(-10, -100)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("blue")
turtle.forward(20)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(20)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.end_fill()

turtle.penup()
turtle.goto(-30, -100)
turtle.pendown()
turtle.begin_fill
turtle.fillcolor("black")
turtle.forward(60)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.forward(60)
turtle.left(90)
turtle.forward(10)
turtle.left(90)
turtle.end_fill()

turtle.penup()
turtle.goto(-5, -90)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("red")
turtle.forward(10)
turtle.left(90)
turtle.forward(150)
turtle.left(45)
turtle.forward(10)
turtle.left(90)
turtle.forward(10)
turtle.left(45)
turtle.forward(150)
turtle.left(90)
turtle.end_fill()

turtle.hideturtle()

turtle.done()